# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170630_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('body', models.TextField(verbose_name='正文')),
                ('create_time', models.DateTimeField(verbose_name='发布日期')),
                ('modified_time', models.DateTimeField(verbose_name='修改日期')),
                ('veiws', models.PositiveIntegerField(default=0, verbose_name='访问量')),
            ],
            options={
                'verbose_name': '关于',
                'verbose_name_plural': '关于',
                'ordering': ['-create_time'],
            },
        ),
    ]
