# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 06:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=20, verbose_name='站点名称')),
                ('site_url', models.URLField(verbose_name='站点链接')),
                ('admin_name', models.CharField(max_length=30, verbose_name='站长名称')),
                ('admin_contact', models.CharField(max_length=200, verbose_name='站长联系方式')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(verbose_name='修改时间')),
                ('is_pub', models.BooleanField(default=False, verbose_name='是否发布')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_visit', models.PositiveIntegerField(default=0, verbose_name='访问量')),
                ('create_date', models.DateTimeField(editable=False, unique=True, verbose_name='日期')),
            ],
            options={
                'verbose_name': '运营统计',
                'verbose_name_plural': '运营统计',
            },
        ),
        migrations.CreateModel(
            name='VisitorRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_host', models.CharField(max_length=200, verbose_name='主机')),
                ('http_path', models.CharField(max_length=200, verbose_name='地址')),
                ('http_user_agent', models.CharField(max_length=400, verbose_name='客户端信息')),
                ('ip', models.CharField(max_length=20, verbose_name='IP')),
                ('server_name', models.CharField(max_length=50, verbose_name='服务器主机名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='请求时间')),
            ],
            options={
                'verbose_name': '访问记录',
                'verbose_name_plural': '访问记录',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-create_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_time',
            field=models.DateTimeField(verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
    ]
