# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-25 13:43
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170711_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumb',
            field=models.ImageField(default='default.jpg', upload_to='uploads/Y%/m%/d%', verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='about',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文'),
        ),
    ]
