# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-09 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170725_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorrecord',
            name='ip',
            field=models.CharField(max_length=30, verbose_name='IP'),
        ),
    ]
