# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-30 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170809_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='uploads/avatar', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
