# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-23 11:12
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180223_1800'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='thumb',
            field=models.ImageField(default='/media/uploads/images/pic05.jpg', upload_to='', verbose_name='图标'),
        ),
    ]
