# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-23 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180223_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
