# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-24 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_word_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='is_pub',
        ),
        migrations.AddField(
            model_name='friendsites',
            name='site_thumb',
            field=models.ImageField(blank=True, upload_to='', verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='post',
            name='word_count',
            field=models.IntegerField(default=0, verbose_name='字数统计'),
        ),
    ]
