# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-24 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180224_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendsites',
            name='site_intro',
            field=models.TextField(blank='没有填写简介', verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='friendsites',
            name='site_url',
            field=models.URLField(verbose_name='链接'),
        ),
    ]
