# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-24 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20180224_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendsites',
            name='is_pub',
            field=models.BooleanField(default=False, verbose_name='是否发布'),
        ),
    ]
