# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-24 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_friendsites_is_pub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendsites',
            name='is_pub',
        ),
    ]
