# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-01-08 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_friendsites_is_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='today_pv',
            field=models.PositiveIntegerField(default=0, verbose_name='今日pv'),
        ),
    ]
